sudo: false
language: node_js

git:
  depth: 1

branches:
  only:
    - master
    - stable
    - develop

node_js:
  - '5'
  - '4'
  - '0.12'

install:
  - npm install fly fly-xo

script:
  - npm test
